### ISSUE TITLE
have a problem

### ISSUE THREAD

**Issue by lijiajun520** [muzairkhattak/ProText#7]
Hello, after I directly git the code and configure the environment, I ran it directly to display this issue without making any changes. Why did this situation occur? I hope to receive an answer. Thank you!

Traceback (most recent call last):
  File "train.py", line 257, in <module>
    main(args)
  File "train.py", line 196, in main
    trainer.test()
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data1/mazc/LJJ/ProText/Dassl.pytorch/dassl/engine/trainer.py", line 464, in test
    output = self.model_inference(input)
  File "/data1/mazc/LJJ/ProText/Dassl.pytorch/dassl/engine/trainer.py", line 476, in model_inference
    return self.model(input)
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/mazc/LJJ/ProText-main/trainers/protext.py", line 191, in forward
    prompted_embedding = self.prompt_learner(self.tokenized_prompts)
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/mazc/LJJ/ProText-main/trainers/protext.py", line 148, in forward
    embedding = self.clip_model_zs.token_embedding(tokenized_prompts)
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    return F.embedding(
  File "/home/mazc/anaconda3/envs/protext/lib/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper__index_select)

**Comment by muzairkhattak** [comment]
Hi @lijiajun520,

Thank you for showing interest in ProText! 

Regarding your query, I think you are running the training code using multiple GPUs. Currently our repository does not support multiple GPU training. In order to fix this issue, you can make sure to use only single GPU. This can be done by using the prefix `CUDA_VISISIBLE_DEVICES=0` before your run command. 

I hope this resolves your issue. Let me know if there are any additional questions.

Kind regards!

**Comment by muzairkhattak** [comment]
I am closing the issue now. Feel free to reopen it if there is still any confusion.
